language: node_js
node_js:
  - "4"
  - "5"
  - "6"
dist: trusty
sudo: required
addons:
  firefox: 46
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script: xvfb-run npm test
