language: node_js
node_js: "10"
dist: xenial
sudo: false
services:
  - xvfb
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: npm run bundle
script: xvfb-run npm test
