language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
addons:
  firefox: latest
  chrome: stable
script:
- npm run bundle
- echo "polymer-analyzer 2.7"
- npm install --no-save polymer-analyzer@2.7
- xvfb-run npm test -- -l chrome
- echo "polymer-analyzer 3"
- npm install --no-save polymer-analyzer@3
- xvfb-run npm test -- -l chrome
